# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'designer.ui'
#
# Created by: PyQt5 UI code generator 5.10.1
#
# WARNING! All changes made in this file will be lost!

from PyQt5 import QtCore, QtGui, QtWidgets

class Ui_MainWindow(object):
    def setupUi(self, MainWindow):
        MainWindow.setObjectName("MainWindow")
        MainWindow.resize(800, 802)
        self.main_tabs = QtWidgets.QWidget(MainWindow)
        self.main_tabs.setObjectName("main_tabs")
        self.lbl_deadline = QtWidgets.QLabel(self.main_tabs)
        self.lbl_deadline.setGeometry(QtCore.QRect(170, 70, 51, 22))
        self.lbl_deadline.setObjectName("lbl_deadline")
        self.line_inportance = QtWidgets.QFrame(self.main_tabs)
        self.line_inportance.setGeometry(QtCore.QRect(390, 290, 20, 441))
        self.line_inportance.setFrameShape(QtWidgets.QFrame.VLine)
        self.line_inportance.setFrameShadow(QtWidgets.QFrame.Sunken)
        self.line_inportance.setObjectName("line_inportance")
        self.tb_plan = QtWidgets.QTableView(self.main_tabs)
        self.tb_plan.setGeometry(QtCore.QRect(370, 10, 421, 281))
        self.tb_plan.setObjectName("tb_plan")
        self.cb_batch_op = QtWidgets.QCheckBox(self.main_tabs)
        self.cb_batch_op.setGeometry(QtCore.QRect(280, 160, 70, 26))
        self.cb_batch_op.setObjectName("cb_batch_op")
        self.calendar_select = QtWidgets.QCalendarWidget(self.main_tabs)
        self.calendar_select.setGeometry(QtCore.QRect(10, 100, 256, 191))
        self.calendar_select.setObjectName("calendar_select")
        self.tb_ac_third = QtWidgets.QTableView(self.main_tabs)
        self.tb_ac_third.setGeometry(QtCore.QRect(10, 520, 381, 201))
        self.tb_ac_third.setObjectName("tb_ac_third")
        self.tb_ac_second = QtWidgets.QTableView(self.main_tabs)
        self.tb_ac_second.setGeometry(QtCore.QRect(10, 300, 381, 201))
        self.tb_ac_second.setObjectName("tb_ac_second")
        self.combo_urgency = QtWidgets.QComboBox(self.main_tabs)
        self.combo_urgency.setGeometry(QtCore.QRect(280, 220, 69, 26))
        self.combo_urgency.setObjectName("combo_urgency")
        self.lbl_begin = QtWidgets.QLabel(self.main_tabs)
        self.lbl_begin.setGeometry(QtCore.QRect(10, 70, 41, 22))
        self.lbl_begin.setObjectName("lbl_begin")
        self.btn_save = QtWidgets.QPushButton(self.main_tabs)
        self.btn_save.setGeometry(QtCore.QRect(280, 260, 71, 26))
        self.btn_save.setObjectName("btn_save")
        self.sb_repeat = QtWidgets.QSpinBox(self.main_tabs)
        self.sb_repeat.setGeometry(QtCore.QRect(280, 130, 71, 26))
        self.sb_repeat.setObjectName("sb_repeat")
        self.combo_frequency = QtWidgets.QComboBox(self.main_tabs)
        self.combo_frequency.setGeometry(QtCore.QRect(280, 100, 69, 26))
        self.combo_frequency.setObjectName("combo_frequency")
        self.le_begin = QtWidgets.QLineEdit(self.main_tabs)
        self.le_begin.setGeometry(QtCore.QRect(50, 70, 91, 22))
        self.le_begin.setObjectName("le_begin")
        self.txt_content = QtWidgets.QTextEdit(self.main_tabs)
        self.txt_content.setGeometry(QtCore.QRect(10, 10, 341, 51))
        self.txt_content.setObjectName("txt_content")
        self.le_deadline = QtWidgets.QLineEdit(self.main_tabs)
        self.le_deadline.setGeometry(QtCore.QRect(230, 70, 91, 22))
        self.le_deadline.setObjectName("le_deadline")
        self.tb_ac_first = QtWidgets.QTableView(self.main_tabs)
        self.tb_ac_first.setGeometry(QtCore.QRect(410, 300, 381, 201))
        self.tb_ac_first.setObjectName("tb_ac_first")
        self.combo_importance = QtWidgets.QComboBox(self.main_tabs)
        self.combo_importance.setGeometry(QtCore.QRect(280, 190, 69, 26))
        self.combo_importance.setObjectName("combo_importance")
        self.tb_ac_fourth = QtWidgets.QTableView(self.main_tabs)
        self.tb_ac_fourth.setGeometry(QtCore.QRect(410, 520, 381, 201))
        self.tb_ac_fourth.setObjectName("tb_ac_fourth")
        self.line_urgency = QtWidgets.QFrame(self.main_tabs)
        self.line_urgency.setGeometry(QtCore.QRect(0, 500, 791, 16))
        self.line_urgency.setFrameShape(QtWidgets.QFrame.HLine)
        self.line_urgency.setFrameShadow(QtWidgets.QFrame.Sunken)
        self.line_urgency.setObjectName("line_urgency")
        MainWindow.setCentralWidget(self.main_tabs)
        self.menubar = QtWidgets.QMenuBar(MainWindow)
        self.menubar.setGeometry(QtCore.QRect(0, 0, 800, 23))
        self.menubar.setObjectName("menubar")
        MainWindow.setMenuBar(self.menubar)
        self.statusbar = QtWidgets.QStatusBar(MainWindow)
        self.statusbar.setObjectName("statusbar")
        MainWindow.setStatusBar(self.statusbar)

        self.retranslateUi(MainWindow)
        QtCore.QMetaObject.connectSlotsByName(MainWindow)

    def retranslateUi(self, MainWindow):
        _translate = QtCore.QCoreApplication.translate
        MainWindow.setWindowTitle(_translate("MainWindow", "MainWindow"))
        self.lbl_deadline.setText(_translate("MainWindow", "Deadline"))
        self.cb_batch_op.setText(_translate("MainWindow", "Batch Op"))
        self.lbl_begin.setText(_translate("MainWindow", "Begin "))
        self.btn_save.setText(_translate("MainWindow", "PushButton"))

